'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Icon } from '@iconify/react';
import { ChevronRight, Folder, FileCode, FileJson, Minus, Terminal, Hash, Settings, Info } from 'lucide-react';

const folderStructureData = {
    name: "my-stack-project",
    path: "my-stack-project",
    type: "folder",
    icon: "catppuccin:folder-root",
    open: true,
    children: [
        {
            name: "frontend",
            path: "my-stack-project / frontend",
            type: "folder",
            icon: "catppuccin:folder-src",
            open: true,
            children: [
                {
                    name: "app",
                    path: "my-stack-project / frontend / app",
                    type: "folder",
                    icon: "catppuccin:folder-app",
                    open: true,
                    children: [
                        {
                            name: "layout.tsx",
                            path: "my-stack-project / frontend / app / layout.tsx",
                            type: "file",
                            icon: "catppuccin:nextjs",
                            content: `import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Stack Struct App",
  description: "Generated by Stack Struct",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>{children}</body>
    </html>
  );
}`
                        },
                        {
                            name: "page.tsx",
                            path: "my-stack-project / frontend / app / page.tsx",
                            type: "file",
                            icon: "catppuccin:nextjs",
                            content: `import Hero from "@/components/Hero";
import Features from "@/components/Features";

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center">
      <Hero />
      <Features />
    </main>
  );
}`
                        },
                    ]
                },
                { name: "components", path: "my-stack-project / frontend / components", type: "folder", icon: "catppuccin:folder-components" },
                { name: "lib", path: "my-stack-project / frontend / lib", type: "folder", icon: "catppuccin:folder-lib" },
            ]
        },
        {
            name: "backend",
            path: "my-stack-project / backend",
            type: "folder",
            icon: "catppuccin:folder-api",
            children: [
                { name: "src", path: "my-stack-project / backend / src", type: "folder", icon: "catppuccin:folder-src" },
                { name: "prisma", path: "my-stack-project / backend / prisma", type: "folder", icon: "catppuccin:folder-database" },
                {
                    name: "package.json",
                    path: "my-stack-project / backend / package.json",
                    type: "file",
                    icon: "catppuccin:json",
                    content: `{
  "name": "stack-backend",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "ts-node-dev src/index.ts",
    "build": "tsc",
    "start": "node dist/index.js"
  },
  "dependencies": {
    "express": "^4.18.2",
    "@prisma/client": "^5.0.0"
  }
}`
                },
            ]
        },
        {
            name: "README.md",
            path: "my-stack-project / README.md",
            type: "file",
            icon: "catppuccin:markdown",
            content: `# Stack Struct Project

This project structure was generated with optimized defaults.

## Getting Started

1. **Install dependencies**:
   \`\`\`bash
   npm install
   \`\`\`

2. **Run dev server**:
   \`\`\`bash
   npm run dev
   \`\`\`

Created with [Stack Struct](https://stackstruct.com)`
        },
    ]
};

function SyntaxHighlighter({ content }) {
    if (!content) return null;

    const lines = content.split('\n');

    // Very basic "highlighter" using simple rules
    const highlight = (line) => {
        // Comments
        if (line.trim().startsWith('//')) return <span className="text-zinc-500 italic">{line}</span>;
        if (line.trim().startsWith('#')) return <span className="text-blue-400 font-bold">{line}</span>;

        // Keywords
        const keywords = ['import', 'export', 'default', 'function', 'const', 'return', 'from', 'if', 'else', 'true', 'false'];

        let elements = [];

        const words = line.split(/(\s+|[{}()[\],./:;<>!=+*-])/);

        words.forEach((word, i) => {
            if (keywords.includes(word)) {
                elements.push(<span key={i} className="text-[#c678dd]">{word}</span>);
            } else if (word.startsWith('"') || word.startsWith("'") || word.startsWith("`")) {
                elements.push(<span key={i} className="text-[#98c379]">{word}</span>);
            } else if (!isNaN(word) && word !== "") {
                elements.push(<span key={i} className="text-[#d19a66]">{word}</span>);
            } else if (/^[A-Z][a-zA-Z0-9]*$/.test(word)) {
                elements.push(<span key={i} className="text-[#e5c07b]">{word}</span>);
            } else if (word === '{' || word === '}' || word === '(' || word === ')' || word === '[' || word === ']') {
                elements.push(<span key={i} className="text-[#abb2bf]">{word}</span>);
            } else {
                elements.push(word);
            }
        });

        return elements;
    };

    return (
        <div className="flex w-full">
            {/* Line Numbers */}
            <div className="w-12 pr-4 text-right select-none border-r border-white/5 mr-6 py-1">
                {lines.map((_, i) => (
                    <div key={i} className="text-[#3b3b4f] text-[11px] leading-[22px]">{i + 1}</div>
                ))}
            </div>
            {/* Code */}
            <div className="flex-1 py-1 overflow-x-auto custom-scrollbar">
                {lines.map((line, i) => (
                    <div key={i} className="whitespace-pre leading-[22px] min-h-[22px]">
                        {highlight(line)}
                    </div>
                ))}
            </div>
        </div>
    );
}

export default function FolderStructure() {
    const [selectedFile, setSelectedFile] = useState(folderStructureData.children[0].children[0].children[1]); // Default to page.tsx

    return (
        <section className="bg-black/20 py-32 border-t border-white/5 overflow-hidden">
            <div className="max-w-7xl mx-auto px-6">
                <div className="flex flex-col md:flex-row md:items-end justify-between gap-8 mb-20">
                    <div className="max-w-2xl space-y-4 text-left">
                        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-500/5 border border-blue-500/10 mb-4">
                            <span className="w-1.5 h-1.5 rounded-full bg-blue-400 animate-pulse" />
                            <span className="text-[10px] uppercase tracking-widest font-bold text-blue-400/80">Architecture View</span>
                        </div>
                        <h2 className="text-4xl font-bold tracking-tight text-white/90">
                            Opinionated Project Structure
                        </h2>
                        <p className="text-lg text-muted-foreground/40 leading-relaxed font-light">
                            Professional-grade folder architectures that scale. From microservices to monorepos,
                            move from concept to code in seconds with industry best practices built-in.
                        </p>
                    </div>
                </div>

                <div className="relative group">
                    {/* Background Glows */}
                    <div className="absolute -top-24 -left-24 w-[500px] h-[500px] bg-blue-500/10 rounded-full blur-[120px] opacity-30 pointer-events-none" />
                    <div className="absolute -bottom-24 -right-24 w-[500px] h-[500px] bg-purple-500/10 rounded-full blur-[120px] opacity-30 pointer-events-none" />

                    {/* Integrated IDE Design */}
                    <div className="grid lg:grid-cols-[280px_1fr] h-[650px] rounded-2xl border border-white/5 bg-[#080810] shadow-[0_40px_100px_rgba(0,0,0,0.8)] overflow-hidden">

                        {/* Sidebar (Folder Tree) */}
                        <div className="flex flex-col bg-[#05050a] border-r border-white/5">
                            <div className="flex items-center gap-3 px-5 py-4 bg-white/[0.02] border-b border-white/5">
                                <Icon icon="vscode-icons:folder-type-root" className="h-4 w-4" />
                                <span className="text-[11px] font-bold text-white/40 tracking-[.15em] uppercase">Explorer</span>
                            </div>
                            <div className="flex-1 overflow-y-auto p-4 custom-scrollbar">
                                <FileTreeNode
                                    node={folderStructureData}
                                    onFileSelect={setSelectedFile}
                                    selectedFile={selectedFile}
                                />
                            </div>
                            <div className="p-4 border-t border-white/5 bg-white/[0.01] flex items-center justify-between opacity-40">
                                <div className="flex gap-3">
                                    <Settings className="h-3.5 w-3.5" />
                                    <Info className="h-3.5 w-3.5" />
                                </div>
                                <span className="text-[10px] font-mono">v1.2.0</span>
                            </div>
                        </div>

                        {/* Main Editor Section */}
                        <div className="flex flex-col bg-[#0b0b14]/50">
                            {/* Editor Tabs & Breadcrumbs */}
                            <div className="bg-[#05050a] border-b border-white/5">
                                <div className="flex">
                                    <div className="px-5 py-3.5 bg-[#0b0b14] border-r border-white/5 border-t-2 border-t-blue-500 flex items-center gap-3">
                                        <Icon icon={selectedFile?.icon || "lucide:file-code"} className="h-3.5 w-3.5" />
                                        <span className="text-[13px] font-medium text-white/90">{selectedFile?.name || "Code Preview"}</span>
                                        <Minus className="h-3 w-3 opacity-20" />
                                    </div>
                                    <div className="flex-1 px-4 flex items-center bg-[#05050a] opacity-30">
                                        <div className="flex items-center gap-2 text-[11px] font-mono tracking-tight">
                                            <span>{selectedFile?.path || "Select a file..."}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* Editor Body */}
                            <div className="flex-1 overflow-hidden relative">
                                <AnimatePresence mode="wait">
                                    <motion.div
                                        key={selectedFile?.name}
                                        initial={{ opacity: 0, x: 8 }}
                                        animate={{ opacity: 1, x: 0 }}
                                        exit={{ opacity: 0, x: -8 }}
                                        transition={{ duration: 0.25, ease: "easeOut" }}
                                        className="h-full"
                                    >
                                        <div className="h-full p-6 font-mono text-[13px] leading-relaxed overflow-auto custom-scrollbar bg-black/30">
                                            {selectedFile?.content ? (
                                                <SyntaxHighlighter content={selectedFile.content} />
                                            ) : (
                                                <div className="h-full flex flex-col items-center justify-center text-muted-foreground/10 space-y-6">
                                                    <Icon icon="lucide:file-code" className="h-20 w-20 opacity-10" />
                                                    <p className="text-sm italic tracking-wide">Select a file from the explorer to preview the structure</p>
                                                </div>
                                            )}
                                        </div>
                                    </motion.div>
                                </AnimatePresence>
                            </div>

                            {/* Status Bar */}
                            <div className="h-6 bg-blue-600/90 flex items-center justify-between px-4 text-[10px] text-white/90 font-medium">
                                <div className="flex items-center gap-4">
                                    <div className="flex items-center gap-1.5">
                                        <Icon icon="fluent:branch-24-filled" className="h-3 w-3" />
                                        <span>main*</span>
                                    </div>
                                    <div className="flex items-center gap-1.5">
                                        <Icon icon="mdi:sync" className="h-3 w-3" />
                                        <span>0</span>
                                    </div>
                                </div>
                                <div className="flex items-center gap-4">
                                    <span>UTF-8</span>
                                    <span>TypeScript JSX</span>
                                    <div className="flex items-center gap-1">
                                        <Icon icon="mdi:bell-outline" className="h-3 w-3" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    );
}

function FileTreeNode({ node, onFileSelect, selectedFile, depth = 0 }) {
    const [isOpen, setIsOpen] = useState(node.open || false);
    const isFolder = node.type === 'folder';
    const isSelected = selectedFile?.name === node.name;

    const handleClick = () => {
        if (isFolder) {
            setIsOpen(!isOpen);
        } else {
            onFileSelect(node);
        }
    };

    return (
        <div className="select-none">
            <div
                onClick={handleClick}
                className={`flex items-center gap-2.5 py-1 px-3 rounded-md cursor-pointer transition-all duration-200 group ${isSelected ? 'bg-white/5 text-blue-400' : 'text-white/30 hover:text-white/70 hover:bg-white/[0.03]'
                    }`}
                style={{ paddingLeft: `${depth * 16 + 8}px` }}
            >
                {isFolder ? (
                    <ChevronRight className={`h-3 w-3 transition-transform ${isOpen ? 'rotate-90 text-white/60' : 'text-white/10'} group-hover:text-blue-400/50`} />
                ) : (
                    <div className="w-3" />
                )}
                <Icon icon={node.icon} className={`h-4 w-4 shrink-0 transition-all duration-300 ${isFolder ? 'text-blue-500/60 group-hover:text-blue-400' :
                        isSelected ? 'text-blue-400' : 'text-white/20 group-hover:text-white/40'
                    } group-hover:scale-110`} />
                <span className={`text-[12px] font-medium tracking-tight whitespace-nowrap transition-colors ${isSelected ? 'text-blue-400/90' : ''}`}>
                    {node.name}
                </span>
            </div>
            {isFolder && isOpen && node.children && (
                <div className="mt-0.5">
                    {node.children.map((child, idx) => (
                        <FileTreeNode
                            key={`${child.name}-${idx}`}
                            node={child}
                            onFileSelect={onFileSelect}
                            selectedFile={selectedFile}
                            depth={depth + 1}
                        />
                    ))}
                </div>
            )}
        </div>
    );
}
