'use client';

import { motion } from 'framer-motion';
import { Folder, FileJson, FileCode, ChevronRight } from 'lucide-react';

export function LivePreview() {
    return (
        <section className="py-0 relative overflow-hidden">
            <div className="container px-4 md:px-6">
                <div className="flex flex-col items-center justify-center space-y-4 text-center mb-16">
                    <h2 className="text-4xl font-bold tracking-tighter sm:text-4xl">Live Preview</h2>
                    <p className="max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                        Watch your project structure take shape with real-time code previews.
                    </p>
                </div>

                <div className="grid lg:grid-cols-2 gap-8 items-stretch">
                    {/* Folder Tree */}
                    <motion.div
                        initial={{ opacity: 0, x: -20 }}
                        whileInView={{ opacity: 1, x: 0 }}
                        transition={{ duration: 0.6 }}
                        viewport={{ once: true }}
                        className="glass-card p-6 flex flex-col h-[500px]"
                    >
                        <div className="flex items-center gap-2 mb-6 border-b border-white/5 pb-4">
                            <Folder className="h-5 w-5 text-blue-400" />
                            <span className="font-medium">Project Explorer</span>
                        </div>
                        <div className="space-y-3 overflow-y-auto custom-scrollbar pr-2">
                            <TreeItem label="src" icon={<Folder className="h-4 w-4 text-blue-400" />} open>
                                <TreeItem label="app" icon={<Folder className="h-4 w-4 text-blue-400" />} open>
                                    <TreeItem label="api" icon={<Folder className="h-4 w-4 text-blue-400" />} />
                                    <TreeItem label="layout.js" icon={<FileCode className="h-4 w-4 text-yellow-400" />} />
                                    <TreeItem label="page.js" icon={<FileCode className="h-4 w-4 text-yellow-400" />} />
                                </TreeItem>
                                <TreeItem label="components" icon={<Folder className="h-4 w-4 text-blue-400" />} />
                                <TreeItem label="lib" icon={<Folder className="h-4 w-4 text-blue-400" />} />
                            </TreeItem>
                            <TreeItem label="package.json" icon={<FileJson className="h-4 w-4 text-cyan-400" />} />
                            <TreeItem label="README.md" icon={<ChevronRight className="h-4 w-4" />} />
                        </div>
                    </motion.div>

                    {/* Code Preview */}
                    <motion.div
                        initial={{ opacity: 0, x: 20 }}
                        whileInView={{ opacity: 1, x: 0 }}
                        transition={{ duration: 0.6 }}
                        viewport={{ once: true }}
                        className="glass-card flex flex-col h-[500px] overflow-hidden"
                    >
                        <div className="flex items-center justify-between gap-2 px-6 py-4 border-b border-white/5 bg-white/2">
                            <div className="flex items-center gap-2">
                                <FileCode className="h-5 w-5 text-yellow-400" />
                                <span className="font-medium text-sm">src/app/page.js</span>
                            </div>
                            <div className="flex gap-1.5">
                                <div className="w-3 h-3 rounded-full bg-red-500/50" />
                                <div className="w-3 h-3 rounded-full bg-yellow-500/50" />
                                <div className="w-3 h-3 rounded-full bg-green-500/50" />
                            </div>
                        </div>
                        <div className="p-6 font-mono text-sm overflow-y-auto custom-scrollbar flex-1 bg-black/20">
                            <pre className="text-blue-300">
                                {`export default function Page() {\n  return (\n    <main className="container">\n      <h1 className="text-4xl">Hello World</h1>\n      <p>Project generated by Stack Struct</p>\n    </main>\n  );\n}`}
                            </pre>
                        </div>
                    </motion.div>
                </div>
            </div>
        </section>
    );
}

function TreeItem({ label, icon, children, open = false }) {
    return (
        <div className="space-y-2">
            <div className="flex items-center gap-2 hover:bg-white/5 p-1 rounded cursor-pointer transition-colors group">
                {children && <ChevronRight className={`h-3 w-3 transition-transform ${open ? 'rotate-90' : ''}`} />}
                {!children && <div className="w-3" />}
                {icon}
                <span className="text-sm group-hover:text-white transition-colors">{label}</span>
            </div>
            {open && children && (
                <div className="ml-6 border-l border-white/10 space-y-2">
                    {children}
                </div>
            )}
        </div>
    );
}
