import { getFolder, getFile } from "../../utils/tree-nodes";

/**
 * Resolves the base structure for a Next.js App Router project.
 */
export function nextFramework(config) {
  const isTS =
    config.language === "typescript" || config.language === undefined;

  const ext = isTS ? "tsx" : "jsx";
  const logoUrl = process.env.LOGOURL;

  return [
    // app directory (App Router)
    getFolder("app", [
      getFile(
        `layout.${ext}`,
        `
import "./globals.css";

export const metadata = {
  title: "StackStruct App",
  description: "Generated by StackStruct",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
        `.trim(),
      ),

      getFile(
        `page.${ext}`,
        `
export default function HomePage() {
  const logoUrl = ${logoUrl}; // Placeholder logo or use local

  return (
    <div className="min-h-screen bg-gray-950 text-gray-100 flex flex-col">
      {/* Main Content */}
      <main className="flex-1 flex items-center justify-center px-6">
        <div className="text-center max-w-xl">
          <div className="flex items-center justify-center flex-col gap-6 mb-16">
            <div className="relative w-40 h-40 flex items-center justify-center">
              {/* Outer Ring */}
              <div className="absolute inset-0 border border-gray-700/60 rounded-full animate-[spin_4s_linear_infinite]">
                 <div className="h-2.5 w-2.5 bg-gray-400 rounded-full absolute -top-1.5 left-1/2 -translate-x-1/2"></div>
              </div>
              
              {/* Inner Ring */}
              <div className="absolute inset-4 border border-gray-700/60 rounded-full animate-[spin_4s_linear_infinite_reverse]">
                 <div className="h-2.5 w-2.5 bg-gray-400 rounded-full absolute -bottom-1.5 left-1/2 -translate-x-1/2"></div>
              </div>

              {/* Logo */}
              {logoUrl ? (
                <img
                  src={logoUrl}
                  alt="StackStruct Logo"
                  className="h-26 w-26 object-contain rounded-full p-3  absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2"
                />
              ):(<div className="relative z-10 bg-gray-900 rounded-full p-4">
                 <span className="text-4xl">🚀</span>
              </div>)}
            </div>
            
            <h1 className="text-4xl font-bold tracking-tight bg-gradient-to-br from-white to-gray-400 bg-clip-text text-transparent">
              Stack-Struct (Next.js)
            </h1>
          </div>
          
          <h2 className="text-xl font-medium mb-4 text-gray-200">
            Your project is ready.
          </h2>

          <p className="text-gray-400 text-sm leading-relaxed">
            Start building inside <code className="text-indigo-400 font-mono bg-indigo-500/10 px-1 py-0.5 rounded">src/app/</code>.
            This structure was generated using StackStruct.
          </p>

          <div className="mt-8 text-sm text-gray-500 rounded-lg p-4 bg-gray-900/50 border border-gray-800">
            Edit <code className="text-gray-300">page.${ext}</code> to get started.
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-800 py-6 text-center text-xs text-gray-600">
        Generated with StackStruct
      </footer>
    </div>
  );
}
        `.trim(),
      ),
      getFile(
        "globals.css",
        `
@tailwind base;
@tailwind components;
@tailwind utilities;
      `.trim(),
      ),
    ]),

    // next config
    getFile(
      isTS ? "next.config.mjs" : "next.config.js",
      `
/** @type {import('next').NextConfig} */
const nextConfig = {};

export default nextConfig;
      `.trim(),
    ),

    // tsconfig only if TS
    ...(isTS
      ? [
          getFile(
            "tsconfig.json",
            JSON.stringify(
              {
                compilerOptions: {
                  lib: ["dom", "dom.iterable", "esnext"],
                  allowJs: true,
                  skipLibCheck: true,
                  strict: true,
                  noEmit: true,
                  esModuleInterop: true,
                  module: "esnext",
                  moduleResolution: "bundler",
                  resolveJsonModule: true,
                  isolatedModules: true,
                  jsx: "preserve",
                  incremental: true,
                  plugins: [
                    {
                      name: "next",
                    },
                  ],
                  paths: {
                    "@/*": ["./*"],
                  },
                },
                include: [
                  "next-env.d.ts",
                  "**/*.ts",
                  "**/*.tsx",
                  ".next/types/**/*.ts",
                ],
                exclude: ["node_modules"],
              },
              null,
              2,
            ),
          ),
          getFile(
            "next-env.d.ts",
            `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/basic-features/typescript for more information.
            `.trim(),
          ),
        ]
      : []),

    // package.json
    getFile(
      "package.json",
      JSON.stringify(
        {
          name: "my-next-app",
          private: true,
          version: "0.1.0",
          scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
            lint: "next lint",
          },
          dependencies: {
            next: "14.1.0",
            react: "18.2.0",
            "react-dom": "18.2.0",
          },
          devDependencies: isTS
            ? {
                typescript: "^5.0.0",
                "@types/react": "^18.0.0",
                "@types/node": "^20.0.0",
                "@types/react-dom": "^18.0.0",
                tailwindcss: "^3.3.0",
                postcss: "^8.4.0",
                autoprefixer: "^10.4.0",
              }
            : {
                tailwindcss: "^3.3.0",
                postcss: "^8.4.0",
                autoprefixer: "^10.4.0",
              },
        },
        null,
        2,
      ),
    ),
  ];
}
